name: Testbuild

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with: 
                submodules: 'true'
            - run: echo Starting
            - run: sudo apt install uuid-dev
            - run: make toolchain
            - run: make compile
            - run: make image
            - run: ls -lah
            - run: echo Done
